draw_healthbar(hud.shieldsPortHPLeftBound, 
               hud.shieldsPortHPUpperBound, 
               hud.shieldsPortHPRightBound, 
               hud.shieldsPortHPLowerBound, 
               (player.currentHPShieldsPort / player.maxHPShieldsPort) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(hud.shieldsPortHPLeftBound,
          hud.shieldsPortHPUpperBound,
          hud.shieldsPortHPLeftBound,
          hud.shieldsPortHPLowerBound);
draw_line(hud.shieldsPortHPRightBound,
          hud.shieldsPortHPUpperBound,
          hud.shieldsPortHPRightBound,
          hud.shieldsPortHPLowerBound);
draw_line(hud.shieldsPortHPLeftBound,
          hud.shieldsPortHPUpperBound,
          hud.shieldsPortHPRightBound,
          hud.shieldsPortHPUpperBound);
draw_line(hud.shieldsPortHPLeftBound,
          hud.shieldsPortHPLowerBound,
          hud.shieldsPortHPRightBound,
          hud.shieldsPortHPLowerBound);
draw_healthbar(hud.shieldsPortPPLeftBound, 
               hud.shieldsPortPPUpperBound, 
               hud.shieldsPortPPRightBound, 
               hud.shieldsPortPPLowerBound, 
               (player.currentPPShieldsPort / player.requiredPPShields) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(hud.shieldsPortPPLeftBound,
          hud.shieldsPortPPUpperBound,
          hud.shieldsPortPPLeftBound,
          hud.shieldsPortPPLowerBound);
draw_line(hud.shieldsPortPPRightBound,
          hud.shieldsPortPPUpperBound,
          hud.shieldsPortPPRightBound,
          hud.shieldsPortPPLowerBound);
draw_line(hud.shieldsPortPPLeftBound,
          hud.shieldsPortPPUpperBound,
          hud.shieldsPortPPRightBound,
          hud.shieldsPortPPUpperBound);
draw_line(hud.shieldsPortPPLeftBound,
          hud.shieldsPortPPLowerBound,
          hud.shieldsPortPPRightBound,
          hud.shieldsPortPPLowerBound);
draw_set_color(c_white);
draw_line(hud.shieldsPortPPRightBound,
          hud.shieldsPortPPUpperBound,
          hud.shieldsLeftBound + ((hud.shieldsRightBound - hud.shieldsLeftBound) / 2) - (player.sprite_width / 2),
          hud.shieldsUpperBound + ((hud.shieldsLowerBound - hud.shieldsUpperBound) / 2));
