draw_healthbar(global.hud.thrustersBowHPLeftBound, 
               global.hud.thrustersBowHPUpperBound, 
               global.hud.thrustersBowHPRightBound, 
               global.hud.thrustersBowHPLowerBound, 
               (global.player.currentHPThrustersBow / global.player.maxHPThrustersBow) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(global.hud.thrustersBowHPLeftBound,
          global.hud.thrustersBowHPUpperBound,
          global.hud.thrustersBowHPLeftBound,
          global.hud.thrustersBowHPLowerBound);
draw_line(global.hud.thrustersBowHPRightBound,
          global.hud.thrustersBowHPUpperBound,
          global.hud.thrustersBowHPRightBound,
          global.hud.thrustersBowHPLowerBound);
draw_line(global.hud.thrustersBowHPLeftBound,
          global.hud.thrustersBowHPUpperBound,
          global.hud.thrustersBowHPRightBound,
          global.hud.thrustersBowHPUpperBound);
draw_line(global.hud.thrustersBowHPLeftBound,
          global.hud.thrustersBowHPLowerBound,
          global.hud.thrustersBowHPRightBound,
          global.hud.thrustersBowHPLowerBound);
draw_healthbar(global.hud.thrustersBowPPLeftBound, 
               global.hud.thrustersBowPPUpperBound, 
               global.hud.thrustersBowPPRightBound, 
               global.hud.thrustersBowPPLowerBound, 
               (global.player.currentPPThrustersBow / global.player.requiredPPThrusters) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(global.hud.thrustersBowPPLeftBound,
          global.hud.thrustersBowPPUpperBound,
          global.hud.thrustersBowPPLeftBound,
          global.hud.thrustersBowPPLowerBound);
draw_line(global.hud.thrustersBowPPRightBound,
          global.hud.thrustersBowPPUpperBound,
          global.hud.thrustersBowPPRightBound,
          global.hud.thrustersBowPPLowerBound);
draw_line(global.hud.thrustersBowPPLeftBound,
          global.hud.thrustersBowPPUpperBound,
          global.hud.thrustersBowPPRightBound,
          global.hud.thrustersBowPPUpperBound);
draw_line(global.hud.thrustersBowPPLeftBound,
          global.hud.thrustersBowPPLowerBound,
          global.hud.thrustersBowPPRightBound,
          global.hud.thrustersBowPPLowerBound);
draw_set_color(c_white);
draw_line(global.hud.thrustersBowHPLeftBound,
          global.hud.thrustersBowHPUpperBound,
          global.hud.thrustersLeftBound + ((global.hud.thrustersRightBound - global.hud.thrustersLeftBound) / 2),
          global.hud.thrustersUpperBound + ((global.hud.thrustersLowerBound - global.hud.thrustersUpperBound) / 2) - (global.player.sprite_height / 2));
