draw_healthbar(hud.thrustersPortHPLeftBound, 
               hud.thrustersPortHPUpperBound, 
               hud.thrustersPortHPRightBound, 
               hud.thrustersPortHPLowerBound, 
               (player.currentHPThrustersPort / player.maxHPThrustersPort) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(hud.thrustersPortHPLeftBound,
          hud.thrustersPortHPUpperBound,
          hud.thrustersPortHPLeftBound,
          hud.thrustersPortHPLowerBound);
draw_line(hud.thrustersPortHPRightBound,
          hud.thrustersPortHPUpperBound,
          hud.thrustersPortHPRightBound,
          hud.thrustersPortHPLowerBound);
draw_line(hud.thrustersPortHPLeftBound,
          hud.thrustersPortHPUpperBound,
          hud.thrustersPortHPRightBound,
          hud.thrustersPortHPUpperBound);
draw_line(hud.thrustersPortHPLeftBound,
          hud.thrustersPortHPLowerBound,
          hud.thrustersPortHPRightBound,
          hud.thrustersPortHPLowerBound);
draw_healthbar(hud.thrustersPortPPLeftBound, 
               hud.thrustersPortPPUpperBound, 
               hud.thrustersPortPPRightBound, 
               hud.thrustersPortPPLowerBound, 
               (player.currentPPThrustersPort / player.requiredPPThrusters) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(hud.thrustersPortPPLeftBound,
          hud.thrustersPortPPUpperBound,
          hud.thrustersPortPPLeftBound,
          hud.thrustersPortPPLowerBound);
draw_line(hud.thrustersPortPPRightBound,
          hud.thrustersPortPPUpperBound,
          hud.thrustersPortPPRightBound,
          hud.thrustersPortPPLowerBound);
draw_line(hud.thrustersPortPPLeftBound,
          hud.thrustersPortPPUpperBound,
          hud.thrustersPortPPRightBound,
          hud.thrustersPortPPUpperBound);
draw_line(hud.thrustersPortPPLeftBound,
          hud.thrustersPortPPLowerBound,
          hud.thrustersPortPPRightBound,
          hud.thrustersPortPPLowerBound);
draw_set_color(c_white);
draw_line(hud.thrustersPortPPRightBound,
          hud.thrustersPortPPUpperBound,
          hud.thrustersLeftBound + ((hud.thrustersRightBound - hud.thrustersLeftBound) / 2) - (player.sprite_width / 2),
          hud.thrustersUpperBound + ((hud.thrustersLowerBound - hud.thrustersUpperBound) / 2));
