draw_healthbar(global.hud.shieldsBowHPLeftBound, 
               global.hud.shieldsBowHPUpperBound, 
               global.hud.shieldsBowHPRightBound, 
               global.hud.shieldsBowHPLowerBound, 
               (global.player.currentHPShieldsBow / global.player.maxHPShieldsBow) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(global.hud.shieldsBowHPLeftBound,
          global.hud.shieldsBowHPUpperBound,
          global.hud.shieldsBowHPLeftBound,
          global.hud.shieldsBowHPLowerBound);
draw_line(global.hud.shieldsBowHPRightBound,
          global.hud.shieldsBowHPUpperBound,
          global.hud.shieldsBowHPRightBound,
          global.hud.shieldsBowHPLowerBound);
draw_line(global.hud.shieldsBowHPLeftBound,
          global.hud.shieldsBowHPUpperBound,
          global.hud.shieldsBowHPRightBound,
          global.hud.shieldsBowHPUpperBound);
draw_line(global.hud.shieldsBowHPLeftBound,
          global.hud.shieldsBowHPLowerBound,
          global.hud.shieldsBowHPRightBound,
          global.hud.shieldsBowHPLowerBound);
draw_healthbar(global.hud.shieldsBowPPLeftBound, 
               global.hud.shieldsBowPPUpperBound, 
               global.hud.shieldsBowPPRightBound, 
               global.hud.shieldsBowPPLowerBound, 
               (global.player.currentPPShieldsBow / global.player.requiredPPShields) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(global.hud.shieldsBowPPLeftBound,
          global.hud.shieldsBowPPUpperBound,
          global.hud.shieldsBowPPLeftBound,
          global.hud.shieldsBowPPLowerBound);
draw_line(global.hud.shieldsBowPPRightBound,
          global.hud.shieldsBowPPUpperBound,
          global.hud.shieldsBowPPRightBound,
          global.hud.shieldsBowPPLowerBound);
draw_line(global.hud.shieldsBowPPLeftBound,
          global.hud.shieldsBowPPUpperBound,
          global.hud.shieldsBowPPRightBound,
          global.hud.shieldsBowPPUpperBound);
draw_line(global.hud.shieldsBowPPLeftBound,
          global.hud.shieldsBowPPLowerBound,
          global.hud.shieldsBowPPRightBound,
          global.hud.shieldsBowPPLowerBound);
draw_set_color(c_white);
draw_line(global.hud.shieldsBowHPLeftBound,
          global.hud.shieldsBowHPUpperBound,
          global.hud.shieldsLeftBound + ((global.hud.shieldsRightBound - global.hud.shieldsLeftBound) / 2),
          global.hud.shieldsUpperBound + ((global.hud.shieldsLowerBound - global.hud.shieldsUpperBound) / 2) - (global.player.sprite_height / 2));
