draw_healthbar(global.hud.thrustersSternHPLeftBound, 
               global.hud.thrustersSternHPUpperBound, 
               global.hud.thrustersSternHPRightBound, 
               global.hud.thrustersSternHPLowerBound, 
               (global.player.currentHPThrustersStern / global.player.maxHPThrustersStern) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(global.hud.thrustersSternHPLeftBound,
          global.hud.thrustersSternHPUpperBound,
          global.hud.thrustersSternHPLeftBound,
          global.hud.thrustersSternHPLowerBound);
draw_line(global.hud.thrustersSternHPRightBound,
          global.hud.thrustersSternHPUpperBound,
          global.hud.thrustersSternHPRightBound,
          global.hud.thrustersSternHPLowerBound);
draw_line(global.hud.thrustersSternHPLeftBound,
          global.hud.thrustersSternHPUpperBound,
          global.hud.thrustersSternHPRightBound,
          global.hud.thrustersSternHPUpperBound);
draw_line(global.hud.thrustersSternHPLeftBound,
          global.hud.thrustersSternHPLowerBound,
          global.hud.thrustersSternHPRightBound,
          global.hud.thrustersSternHPLowerBound);
draw_healthbar(global.hud.thrustersSternPPLeftBound, 
               global.hud.thrustersSternPPUpperBound, 
               global.hud.thrustersSternPPRightBound, 
               global.hud.thrustersSternPPLowerBound, 
               (global.player.currentPPThrustersStern / global.player.requiredPPThrusters) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(global.hud.thrustersSternPPLeftBound,
          global.hud.thrustersSternPPUpperBound,
          global.hud.thrustersSternPPLeftBound,
          global.hud.thrustersSternPPLowerBound);
draw_line(global.hud.thrustersSternPPRightBound,
          global.hud.thrustersSternPPUpperBound,
          global.hud.thrustersSternPPRightBound,
          global.hud.thrustersSternPPLowerBound);
draw_line(global.hud.thrustersSternPPLeftBound,
          global.hud.thrustersSternPPUpperBound,
          global.hud.thrustersSternPPRightBound,
          global.hud.thrustersSternPPUpperBound);
draw_line(global.hud.thrustersSternPPLeftBound,
          global.hud.thrustersSternPPLowerBound,
          global.hud.thrustersSternPPRightBound,
          global.hud.thrustersSternPPLowerBound);
draw_set_color(c_white);
draw_line(global.hud.thrustersSternPPRightBound,
          global.hud.thrustersSternPPLowerBound,
          global.hud.thrustersLeftBound + ((global.hud.thrustersRightBound - global.hud.thrustersLeftBound) / 2),
          global.hud.thrustersUpperBound + ((global.hud.thrustersLowerBound - global.hud.thrustersUpperBound) / 2) + (global.player.sprite_height / 2));
