draw_healthbar(hud.shieldsBowHPLeftBound, 
               hud.shieldsBowHPUpperBound, 
               hud.shieldsBowHPRightBound, 
               hud.shieldsBowHPLowerBound, 
               (player.currentHPShieldsBow / player.maxHPShieldsBow) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(hud.shieldsBowHPLeftBound,
          hud.shieldsBowHPUpperBound,
          hud.shieldsBowHPLeftBound,
          hud.shieldsBowHPLowerBound);
draw_line(hud.shieldsBowHPRightBound,
          hud.shieldsBowHPUpperBound,
          hud.shieldsBowHPRightBound,
          hud.shieldsBowHPLowerBound);
draw_line(hud.shieldsBowHPLeftBound,
          hud.shieldsBowHPUpperBound,
          hud.shieldsBowHPRightBound,
          hud.shieldsBowHPUpperBound);
draw_line(hud.shieldsBowHPLeftBound,
          hud.shieldsBowHPLowerBound,
          hud.shieldsBowHPRightBound,
          hud.shieldsBowHPLowerBound);
draw_healthbar(hud.shieldsBowPPLeftBound, 
               hud.shieldsBowPPUpperBound, 
               hud.shieldsBowPPRightBound, 
               hud.shieldsBowPPLowerBound, 
               (player.currentPPShieldsBow / player.requiredPPShields) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(hud.shieldsBowPPLeftBound,
          hud.shieldsBowPPUpperBound,
          hud.shieldsBowPPLeftBound,
          hud.shieldsBowPPLowerBound);
draw_line(hud.shieldsBowPPRightBound,
          hud.shieldsBowPPUpperBound,
          hud.shieldsBowPPRightBound,
          hud.shieldsBowPPLowerBound);
draw_line(hud.shieldsBowPPLeftBound,
          hud.shieldsBowPPUpperBound,
          hud.shieldsBowPPRightBound,
          hud.shieldsBowPPUpperBound);
draw_line(hud.shieldsBowPPLeftBound,
          hud.shieldsBowPPLowerBound,
          hud.shieldsBowPPRightBound,
          hud.shieldsBowPPLowerBound);
draw_set_color(c_white);
draw_line(hud.shieldsBowHPLeftBound,
          hud.shieldsBowHPUpperBound,
          hud.shieldsLeftBound + ((hud.shieldsRightBound - hud.shieldsLeftBound) / 2),
          hud.shieldsUpperBound + ((hud.shieldsLowerBound - hud.shieldsUpperBound) / 2) - (player.sprite_height / 2));
