draw_healthbar(hud.thrustersStarboardHPLeftBound, 
               hud.thrustersStarboardHPUpperBound, 
               hud.thrustersStarboardHPRightBound, 
               hud.thrustersStarboardHPLowerBound, 
               (player.currentHPThrustersStarboard / player.maxHPThrustersStarboard) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(hud.thrustersStarboardHPLeftBound,
          hud.thrustersStarboardHPUpperBound,
          hud.thrustersStarboardHPLeftBound,
          hud.thrustersStarboardHPLowerBound);
draw_line(hud.thrustersStarboardHPRightBound,
          hud.thrustersStarboardHPUpperBound,
          hud.thrustersStarboardHPRightBound,
          hud.thrustersStarboardHPLowerBound);
draw_line(hud.thrustersStarboardHPLeftBound,
          hud.thrustersStarboardHPUpperBound,
          hud.thrustersStarboardHPRightBound,
          hud.thrustersStarboardHPUpperBound);
draw_line(hud.thrustersStarboardHPLeftBound,
          hud.thrustersStarboardHPLowerBound,
          hud.thrustersStarboardHPRightBound,
          hud.thrustersStarboardHPLowerBound);
draw_healthbar(hud.thrustersStarboardPPLeftBound, 
               hud.thrustersStarboardPPUpperBound, 
               hud.thrustersStarboardPPRightBound, 
               hud.thrustersStarboardPPLowerBound, 
               (player.currentPPThrustersStarboard / player.requiredPPThrusters) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(hud.thrustersStarboardPPLeftBound,
          hud.thrustersStarboardPPUpperBound,
          hud.thrustersStarboardPPLeftBound,
          hud.thrustersStarboardPPLowerBound);
draw_line(hud.thrustersStarboardPPRightBound,
          hud.thrustersStarboardPPUpperBound,
          hud.thrustersStarboardPPRightBound,
          hud.thrustersStarboardPPLowerBound);
draw_line(hud.thrustersStarboardPPLeftBound,
          hud.thrustersStarboardPPUpperBound,
          hud.thrustersStarboardPPRightBound,
          hud.thrustersStarboardPPUpperBound);
draw_line(hud.thrustersStarboardPPLeftBound,
          hud.thrustersStarboardPPLowerBound,
          hud.thrustersStarboardPPRightBound,
          hud.thrustersStarboardPPLowerBound);
draw_set_color(c_white);
draw_line(hud.thrustersStarboardHPLeftBound,
          hud.thrustersStarboardHPLowerBound,
          hud.thrustersLeftBound + ((hud.thrustersRightBound - hud.thrustersLeftBound) / 2) + (player.sprite_width / 2),
          hud.thrustersUpperBound + ((hud.thrustersLowerBound - hud.thrustersUpperBound) / 2));
