draw_healthbar(global.hud.thrustersStarboardHPLeftBound, 
               global.hud.thrustersStarboardHPUpperBound, 
               global.hud.thrustersStarboardHPRightBound, 
               global.hud.thrustersStarboardHPLowerBound, 
               (global.player.currentHPThrustersStarboard / global.player.maxHPThrustersStarboard) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(global.hud.thrustersStarboardHPLeftBound,
          global.hud.thrustersStarboardHPUpperBound,
          global.hud.thrustersStarboardHPLeftBound,
          global.hud.thrustersStarboardHPLowerBound);
draw_line(global.hud.thrustersStarboardHPRightBound,
          global.hud.thrustersStarboardHPUpperBound,
          global.hud.thrustersStarboardHPRightBound,
          global.hud.thrustersStarboardHPLowerBound);
draw_line(global.hud.thrustersStarboardHPLeftBound,
          global.hud.thrustersStarboardHPUpperBound,
          global.hud.thrustersStarboardHPRightBound,
          global.hud.thrustersStarboardHPUpperBound);
draw_line(global.hud.thrustersStarboardHPLeftBound,
          global.hud.thrustersStarboardHPLowerBound,
          global.hud.thrustersStarboardHPRightBound,
          global.hud.thrustersStarboardHPLowerBound);
draw_healthbar(global.hud.thrustersStarboardPPLeftBound, 
               global.hud.thrustersStarboardPPUpperBound, 
               global.hud.thrustersStarboardPPRightBound, 
               global.hud.thrustersStarboardPPLowerBound, 
               (global.player.currentPPThrustersStarboard / global.player.requiredPPThrusters) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(global.hud.thrustersStarboardPPLeftBound,
          global.hud.thrustersStarboardPPUpperBound,
          global.hud.thrustersStarboardPPLeftBound,
          global.hud.thrustersStarboardPPLowerBound);
draw_line(global.hud.thrustersStarboardPPRightBound,
          global.hud.thrustersStarboardPPUpperBound,
          global.hud.thrustersStarboardPPRightBound,
          global.hud.thrustersStarboardPPLowerBound);
draw_line(global.hud.thrustersStarboardPPLeftBound,
          global.hud.thrustersStarboardPPUpperBound,
          global.hud.thrustersStarboardPPRightBound,
          global.hud.thrustersStarboardPPUpperBound);
draw_line(global.hud.thrustersStarboardPPLeftBound,
          global.hud.thrustersStarboardPPLowerBound,
          global.hud.thrustersStarboardPPRightBound,
          global.hud.thrustersStarboardPPLowerBound);
draw_set_color(c_white);
draw_line(global.hud.thrustersStarboardHPLeftBound,
          global.hud.thrustersStarboardHPLowerBound,
          global.hud.thrustersLeftBound + ((global.hud.thrustersRightBound - global.hud.thrustersLeftBound) / 2) + (global.player.sprite_width / 2),
          global.hud.thrustersUpperBound + ((global.hud.thrustersLowerBound - global.hud.thrustersUpperBound) / 2));
