draw_healthbar(global.hud.shieldsSternHPLeftBound, 
               global.hud.shieldsSternHPUpperBound, 
               global.hud.shieldsSternHPRightBound, 
               global.hud.shieldsSternHPLowerBound, 
               (global.player.currentHPShieldsStern / global.player.maxHPShieldsStern) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(global.hud.shieldsSternHPLeftBound,
          global.hud.shieldsSternHPUpperBound,
          global.hud.shieldsSternHPLeftBound,
          global.hud.shieldsSternHPLowerBound);
draw_line(global.hud.shieldsSternHPRightBound,
          global.hud.shieldsSternHPUpperBound,
          global.hud.shieldsSternHPRightBound,
          global.hud.shieldsSternHPLowerBound);
draw_line(global.hud.shieldsSternHPLeftBound,
          global.hud.shieldsSternHPUpperBound,
          global.hud.shieldsSternHPRightBound,
          global.hud.shieldsSternHPUpperBound);
draw_line(global.hud.shieldsSternHPLeftBound,
          global.hud.shieldsSternHPLowerBound,
          global.hud.shieldsSternHPRightBound,
          global.hud.shieldsSternHPLowerBound);
draw_healthbar(global.hud.shieldsSternPPLeftBound, 
               global.hud.shieldsSternPPUpperBound, 
               global.hud.shieldsSternPPRightBound, 
               global.hud.shieldsSternPPLowerBound, 
               (global.player.currentPPShieldsStern / global.player.requiredPPShields) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(global.hud.shieldsSternPPLeftBound,
          global.hud.shieldsSternPPUpperBound,
          global.hud.shieldsSternPPLeftBound,
          global.hud.shieldsSternPPLowerBound);
draw_line(global.hud.shieldsSternPPRightBound,
          global.hud.shieldsSternPPUpperBound,
          global.hud.shieldsSternPPRightBound,
          global.hud.shieldsSternPPLowerBound);
draw_line(global.hud.shieldsSternPPLeftBound,
          global.hud.shieldsSternPPUpperBound,
          global.hud.shieldsSternPPRightBound,
          global.hud.shieldsSternPPUpperBound);
draw_line(global.hud.shieldsSternPPLeftBound,
          global.hud.shieldsSternPPLowerBound,
          global.hud.shieldsSternPPRightBound,
          global.hud.shieldsSternPPLowerBound);
draw_set_color(c_white);
draw_line(global.hud.shieldsSternPPRightBound,
          global.hud.shieldsSternPPLowerBound,
          global.hud.shieldsLeftBound + ((global.hud.shieldsRightBound - global.hud.shieldsLeftBound) / 2),
          global.hud.shieldsUpperBound + ((global.hud.shieldsLowerBound - global.hud.shieldsUpperBound) / 2) + (global.player.sprite_height / 2));
