draw_healthbar(global.hud.thrustersPortHPLeftBound, 
               global.hud.thrustersPortHPUpperBound, 
               global.hud.thrustersPortHPRightBound, 
               global.hud.thrustersPortHPLowerBound, 
               (global.player.currentHPThrustersPort / global.player.maxHPThrustersPort) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(global.hud.thrustersPortHPLeftBound,
          global.hud.thrustersPortHPUpperBound,
          global.hud.thrustersPortHPLeftBound,
          global.hud.thrustersPortHPLowerBound);
draw_line(global.hud.thrustersPortHPRightBound,
          global.hud.thrustersPortHPUpperBound,
          global.hud.thrustersPortHPRightBound,
          global.hud.thrustersPortHPLowerBound);
draw_line(global.hud.thrustersPortHPLeftBound,
          global.hud.thrustersPortHPUpperBound,
          global.hud.thrustersPortHPRightBound,
          global.hud.thrustersPortHPUpperBound);
draw_line(global.hud.thrustersPortHPLeftBound,
          global.hud.thrustersPortHPLowerBound,
          global.hud.thrustersPortHPRightBound,
          global.hud.thrustersPortHPLowerBound);
draw_healthbar(global.hud.thrustersPortPPLeftBound, 
               global.hud.thrustersPortPPUpperBound, 
               global.hud.thrustersPortPPRightBound, 
               global.hud.thrustersPortPPLowerBound, 
               (global.player.currentPPThrustersPort / global.player.requiredPPThrusters) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(global.hud.thrustersPortPPLeftBound,
          global.hud.thrustersPortPPUpperBound,
          global.hud.thrustersPortPPLeftBound,
          global.hud.thrustersPortPPLowerBound);
draw_line(global.hud.thrustersPortPPRightBound,
          global.hud.thrustersPortPPUpperBound,
          global.hud.thrustersPortPPRightBound,
          global.hud.thrustersPortPPLowerBound);
draw_line(global.hud.thrustersPortPPLeftBound,
          global.hud.thrustersPortPPUpperBound,
          global.hud.thrustersPortPPRightBound,
          global.hud.thrustersPortPPUpperBound);
draw_line(global.hud.thrustersPortPPLeftBound,
          global.hud.thrustersPortPPLowerBound,
          global.hud.thrustersPortPPRightBound,
          global.hud.thrustersPortPPLowerBound);
draw_set_color(c_white);
draw_line(global.hud.thrustersPortPPRightBound,
          global.hud.thrustersPortPPUpperBound,
          global.hud.thrustersLeftBound + ((global.hud.thrustersRightBound - global.hud.thrustersLeftBound) / 2) - (global.player.sprite_width / 2),
          global.hud.thrustersUpperBound + ((global.hud.thrustersLowerBound - global.hud.thrustersUpperBound) / 2));
