draw_healthbar(global.hud.shieldsStarboardHPLeftBound, 
               global.hud.shieldsStarboardHPUpperBound, 
               global.hud.shieldsStarboardHPRightBound, 
               global.hud.shieldsStarboardHPLowerBound, 
               (global.player.currentHPShieldsStarboard / global.player.maxHPShieldsStarboard) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(global.hud.shieldsStarboardHPLeftBound,
          global.hud.shieldsStarboardHPUpperBound,
          global.hud.shieldsStarboardHPLeftBound,
          global.hud.shieldsStarboardHPLowerBound);
draw_line(global.hud.shieldsStarboardHPRightBound,
          global.hud.shieldsStarboardHPUpperBound,
          global.hud.shieldsStarboardHPRightBound,
          global.hud.shieldsStarboardHPLowerBound);
draw_line(global.hud.shieldsStarboardHPLeftBound,
          global.hud.shieldsStarboardHPUpperBound,
          global.hud.shieldsStarboardHPRightBound,
          global.hud.shieldsStarboardHPUpperBound);
draw_line(global.hud.shieldsStarboardHPLeftBound,
          global.hud.shieldsStarboardHPLowerBound,
          global.hud.shieldsStarboardHPRightBound,
          global.hud.shieldsStarboardHPLowerBound);
draw_healthbar(global.hud.shieldsStarboardPPLeftBound, 
               global.hud.shieldsStarboardPPUpperBound, 
               global.hud.shieldsStarboardPPRightBound, 
               global.hud.shieldsStarboardPPLowerBound, 
               (global.player.currentPPShieldsStarboard / global.player.requiredPPShields) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(global.hud.shieldsStarboardPPLeftBound,
          global.hud.shieldsStarboardPPUpperBound,
          global.hud.shieldsStarboardPPLeftBound,
          global.hud.shieldsStarboardPPLowerBound);
draw_line(global.hud.shieldsStarboardPPRightBound,
          global.hud.shieldsStarboardPPUpperBound,
          global.hud.shieldsStarboardPPRightBound,
          global.hud.shieldsStarboardPPLowerBound);
draw_line(global.hud.shieldsStarboardPPLeftBound,
          global.hud.shieldsStarboardPPUpperBound,
          global.hud.shieldsStarboardPPRightBound,
          global.hud.shieldsStarboardPPUpperBound);
draw_line(global.hud.shieldsStarboardPPLeftBound,
          global.hud.shieldsStarboardPPLowerBound,
          global.hud.shieldsStarboardPPRightBound,
          global.hud.shieldsStarboardPPLowerBound);
draw_set_color(c_white);
draw_line(global.hud.shieldsStarboardHPLeftBound,
          global.hud.shieldsStarboardHPLowerBound,
          global.hud.shieldsLeftBound + ((global.hud.shieldsRightBound - global.hud.shieldsLeftBound) / 2) + (global.player.sprite_width / 2),
          global.hud.shieldsUpperBound + ((global.hud.shieldsLowerBound - global.hud.shieldsUpperBound) / 2));
