if(object_index = objRiceCake) {
    gunsArray[0] = x;
    gunsArray[1] = y;
} else if(object_index = objSidecar) {
    gunsArray[0] = x;
    gunsArray[1] = y;
    gunsArray[2] = x;
    gunsArray[3] = y - 25;
} else if(object_index = objFlasher) {
    gunsArray[0] = x - 25;
    gunsArray[1] = y;
    gunsArray[2] = x + 25;
    gunsArray[3] = y;
} else if(object_index = objHalitosis) {
    gunsArray[0] = x;
    gunsArray[1] = y - 25;
    gunsArray[2] = x - 25;
    gunsArray[3] = y - 25;
    gunsArray[4] = x + 25;
    gunsArray[5] = y - 25;
} else if(object_index = objPincer) {
    gunsArray[0] = x - 25;
    gunsArray[1] = y;
    gunsArray[2] = x - 25;
    gunsArray[3] = y - 25;
    gunsArray[4] = x + 25;
    gunsArray[5] = y;
} else if(object_index = objMezzanine) {
    gunsArray[0] = x - 25;
    gunsArray[1] = y - 25;
    gunsArray[2] = x;
    gunsArray[3] = y - 25;
    gunsArray[4] = x + 25;
    gunsArray[5] = y - 25;
    gunsArray[6] = x;
    gunsArray[7] = y;
    gunsArray[8] = x + 25;
    gunsArray[9] = y;
    gunsArray[10] = x + 25;
    gunsArray[11] = y + 25;
} else if(object_index = objPawn) {
    gunsArray[0] = x;
    gunsArray[1] = y;
}
