draw_healthbar(hud.thrustersBowHPLeftBound, 
               hud.thrustersBowHPUpperBound, 
               hud.thrustersBowHPRightBound, 
               hud.thrustersBowHPLowerBound, 
               (player.currentHPThrustersBow / player.maxHPThrustersBow) * 100, 
               c_black, 
               c_maroon, 
               c_maroon, 
               3, 
               false, 
               false);
draw_set_color(c_maroon);
draw_line(hud.thrustersBowHPLeftBound,
          hud.thrustersBowHPUpperBound,
          hud.thrustersBowHPLeftBound,
          hud.thrustersBowHPLowerBound);
draw_line(hud.thrustersBowHPRightBound,
          hud.thrustersBowHPUpperBound,
          hud.thrustersBowHPRightBound,
          hud.thrustersBowHPLowerBound);
draw_line(hud.thrustersBowHPLeftBound,
          hud.thrustersBowHPUpperBound,
          hud.thrustersBowHPRightBound,
          hud.thrustersBowHPUpperBound);
draw_line(hud.thrustersBowHPLeftBound,
          hud.thrustersBowHPLowerBound,
          hud.thrustersBowHPRightBound,
          hud.thrustersBowHPLowerBound);
draw_healthbar(hud.thrustersBowPPLeftBound, 
               hud.thrustersBowPPUpperBound, 
               hud.thrustersBowPPRightBound, 
               hud.thrustersBowPPLowerBound, 
               (player.currentPPThrustersBow / player.requiredPPThrusters) * 100, 
               c_black, 
               c_teal, 
               c_teal, 
               3, 
               false, 
               false);
draw_set_color(c_teal);
draw_line(hud.thrustersBowPPLeftBound,
          hud.thrustersBowPPUpperBound,
          hud.thrustersBowPPLeftBound,
          hud.thrustersBowPPLowerBound);
draw_line(hud.thrustersBowPPRightBound,
          hud.thrustersBowPPUpperBound,
          hud.thrustersBowPPRightBound,
          hud.thrustersBowPPLowerBound);
draw_line(hud.thrustersBowPPLeftBound,
          hud.thrustersBowPPUpperBound,
          hud.thrustersBowPPRightBound,
          hud.thrustersBowPPUpperBound);
draw_line(hud.thrustersBowPPLeftBound,
          hud.thrustersBowPPLowerBound,
          hud.thrustersBowPPRightBound,
          hud.thrustersBowPPLowerBound);
draw_set_color(c_white);
draw_line(hud.thrustersBowHPLeftBound,
          hud.thrustersBowHPUpperBound,
          hud.thrustersLeftBound + ((hud.thrustersRightBound - hud.thrustersLeftBound) / 2),
          hud.thrustersUpperBound + ((hud.thrustersLowerBound - hud.thrustersUpperBound) / 2) - (player.sprite_height / 2));
